name: App deployment to EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3.0
      with:
        version: 'v1.25.0' # default is latest stable
        install-metrics-apiserver: true      

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "v1.1.7"

    - name: Terraform Cloud Validation
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}          
        
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true      
              
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false


    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}
    
    - name: Deploy webapp to EKS
      run: kubectl apply -f webapp/  
    - name: Deploy sockapp to EKS
      run: kubectl apply -f sockapp/
    - name: Set up monitoring
      run: kubectl apply -f manifests-monitoring/    
    - name: Set up CRD
      run: kubectl apply -f https://raw.githubusercontent.com/fluent/fluentd-kubernetes-daemonset/master/fluentd-daemonset-elasticsearch-rbac.yaml  
    - name: Set up logging
      run: kubectl apply -f logging/ 
